name:  Docker Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # This workflow contains a single job called "build"
  docker-build:
    name: Docker build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      #      - name: Login to DockerHub
      #        uses: docker/login-action@v1
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
#          tags: ghcr.io/guy-incognito/...
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
